title: MIDI
url: "https://martlaa.github.io"
baseurl: "/midi"
timezone: Europe/Tallinn
encoding: utf-8
markdown: kramdown
permalink: pretty
strict_front_matter: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - docs
  - vendor
  - scripts
  - .bundle
  - node_modules
  - LICENSE
